### ISSUE TITLE
How to convert

### ISSUE THREAD

**Issue by Nillerbobsen** [AmpedWasTaken/Fivem-Script-Converter#1]
I have no experience with Node and I have no idea how to make it work, I was just wondering if you could help me out?

**Comment by yibtag** [comment]
First you install node from its website https://nodejs.org/en/

Then you create a new folder and open it in youre termianl/command prompt

Then you type the following commands:
```bash
npm init -y
npm i fivem-script-converter
```

Then create a new file in the folder named index.js(! make sure you have file extentions on in youre file explorer)

Then open it in youre text editor and type this init:

```javascript
const converter = require('fivem-script-converter');

// esx to qbus (! make sure to replace the \ in the direcotry with /)
converter.esxtoqbus('path/to/esx/script.lua');

// qbus to esx
converter.qbustoesx('path/to/qbus/script.lua');
```

Then back in youre terminal run the foolowinfg command:
```bash
node index.js
```
